StockScraper/Models/CNNmoneyStock.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNNmoneyStock
    {
        public byte StockId { get; set; }
        public string CompanyName { get; set; }
        public string Price { get; set; }
        public string Change { get; set; }
        public string PercentChange { get; set; }
        public System.DateTime Date { get; set; }
    }
}

StockScraper/Controllers/CNNmoneyStocksController.cs
using HtmlAgilityPack;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StockScraper.Models;
using Database = StockScraper.Services.Database;
using StockScraper.Services;

namespace StockScraper.Controllers
{
    public class CNNmoneyStocksController : Controller
    {
        private StockInfoEntities3 db = new StockInfoEntities3();
        [Authorize]
        // GET: CNNmoneyStocks
        public ActionResult Index()
        {
            return View(db.CNNmoneyStocks.ToList());
        }

        [Authorize]
        // GET: CNNmoneyStocks/Details/5
        public ActionResult HAPScrapeCNNHotStocks()
        {
            if (ModelState.IsValid)
            {
                string html = @"https://money.cnn.com/data/hotstocks/index.html";

                HtmlWeb web = new HtmlWeb();

                HtmlDocument htmlDoc = web.Load(html);

                List<Stock> stockList = new List<Stock>();

                HtmlNodeCollection rowsNodesList = htmlDoc.DocumentNode.SelectNodes("//table[contains(@class, 'wsod_dataTable')]//tr");

                int stockId = 1;
                foreach (var row in rowsNodesList)
                {
                    stockId++;

                    var cells = row.SelectNodes("td");
                    if (cells != null && cells.Count > 0)
                    {
                        var companyName = cells[0].InnerText;
                        var price = cells[1].InnerText;
                        var change = cells[2].InnerText;
                        var percentChange = cells[3].InnerText;


                        Stock newStock = new Stock(stockId, companyName, price, change, percentChange);
                        stockList.Add(newStock);
                        Database.AddCNNMoneyIntoDatabase(newStock);
                    }

                }
            }
            return RedirectToAction("Index");
        }



  
   

        

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockScraper/Views/CNNmoneyStocks/Index.cshtml
@model IEnumerable<StockScraper.Models.CNNmoneyStock>

@{
    ViewBag.Title = "CNN";
}

<h2 class="pt-4 text-center" style="font-family: 'Quattrocento Sans', sans-serif; color: darkslateblue;">
    CNN Hot Stocks with Html Agility-Pack
</h2>
<p class="text-center">
    @Html.ActionLink("Click Here to Get the Most Current Stock Update", "HAPScrapeCNNHotStocks", "CNNmoneyStocks", new { @class = "btn btn-outline-secondary", id = "scraper", role = "button" })
</p>
<br />
<table class="table table-striped" style="font-family: 'Quattrocento Sans', sans-serif;">
    <tr>
        <th>
            Company
        </th>
        <th>
            Price
        </th>
        <th>
            Change
        </th>
        <th>
            % Chg
        </th>
        <th>
            Date
        </th>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Change)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PercentChange)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }

</table>