StockScraper/Models/WorldTradingData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockScraper.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldTradingData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorldTradingData()
        {
            this.WorldTradingDataHistories = new HashSet<WorldTradingDataHistory>();
        }
    
        public string Symbol { get; set; }
        public string Price { get; set; }
        public string OpenPrice { get; set; }
        public string HighPrice { get; set; }
        public string LowPrice { get; set; }
        public string PercentChange { get; set; }
        public string AvgVolume { get; set; }
        public System.DateTime Date { get; set; }
        public int ScrapeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorldTradingDataHistory> WorldTradingDataHistories { get; set; }
    }
}

StockScraper/Controllers/WorldTradingDatasController.cs
using RestSharp;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StockScraper.Models;
using StockScraper.Services;
using Database = StockScraper.Services.Database;

namespace StockScraper.Controllers
{
    public class WorldTradingDatasController : Controller
    {
        private StockInfoEntities1 db = new StockInfoEntities1();

        // GET: WorldTradingDatas
        public ActionResult Index()
        {
            return View(db.WorldTradingDatas.ToList());
        }

        [Authorize]
        public ActionResult CallWTDApiForCurrentInfo()
        {
            if (ModelState.IsValid)
            {
                WorldTradingDataApi newCallToApi = new WorldTradingDataApi();
                var request = newCallToApi.MakeApiRequest();
                var response = newCallToApi.ReceieveApiResponse(request);

                List<CallForStockInfo> allStocks = new List<CallForStockInfo>();

                CallForStockInfo newStock;
                var callForStockInfo = newCallToApi.DeserializeResponse(response);

                for (int stockIndex = 0; stockIndex < WorldTradingDataApi.stocks.Count; stockIndex++)
                {
                    string symbol = callForStockInfo.data[stockIndex].symbol.ToString();
                    string price = callForStockInfo.data[stockIndex].price.ToString();
                    string price_open = callForStockInfo.data[stockIndex].price_open.ToString();
                    string day_high = callForStockInfo.data[stockIndex].day_high.ToString();
                    string day_low = callForStockInfo.data[stockIndex].day_low.ToString();
                    string change_pct = callForStockInfo.data[stockIndex].change_pct.ToString();
                    string volume_avg = callForStockInfo.data[stockIndex].volume_avg.ToString();

                    newStock = new CallForStockInfo(symbol, price, price_open, day_high, day_low,
                        change_pct, volume_avg);
                    allStocks.Add(newStock);
                    Database.MoveWorldTradingDataInfoToHistoryOfStocksTable(newStock);
                    Database.AddCurrentWorldTradingDataInfoIntoDatabase(newStock);
                }

            }
            return RedirectToAction("Index");
        }

        // GET: WorldTradingDatas/Details/5
        [Authorize]
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WorldTradingData worldTradingData = db.WorldTradingDatas.Find(id);
            if (worldTradingData == null)
            {
                return HttpNotFound();
            }
            return View(worldTradingData);
        }

     
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StockScraper/Views/WorldTradingDatas/Index.cshtml
@model IEnumerable<StockScraper.Models.WorldTradingData>

@{
    ViewBag.Title = "WTD";
}

<h2 class="pt-4 text-center" style="font-family: 'Quattrocento Sans', sans-serif; color: darkslateblue;">
    World Trading Data with RestSharp
</h2>
<br />
<p class="text-center">
    @Html.ActionLink("Click Here to Get the Most Current Stock Update", "CallWTDApiForCurrentInfo", "WorldTradingDatas", new { @class = "btn btn-outline-secondary", id = "scraper", role = "button" })
</p>
<br />
<table class="table table-striped" style="font-family: 'Quattrocento Sans', sans-serif;">
    <tr>
        <th>
            Symbol
        </th>
        <th>
            Price
        </th>
        <th>
            Open
        </th>
        <th>
            High
        </th>
        <th>
            Low
        </th>
        <th>
            % Change
        </th>
        <th>
            Avg Vol
        </th>
        <th>
            Date
        </th>
     
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Symbol)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpenPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HighPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LowPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PercentChange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AvgVolume)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }

</table>